name: Docker Compose Exercise
run-name: ${{ github.actor }} run 3 containers at same time
on: [push]
jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    # Checkout Repository
    - uses: actions/checkout@v3
    # Run Docker Compose up
    - name: docker compose
      run: docker compose up -d
    # setup node environment
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    # install current dependencies in sub-directory
    - name: install dependencies
      working-directory: ./app
      run: npm install
    # run current tests in sub-directory
    - name: run tests
      working-directory: ./app
      run: npm test
